### ISSUE TITLE
Execution time increases exponentially with the length of sorted string value

### ISSUE THREAD

**Issue by JordanAtBridgit** [yobacca/natural-orderby#101]
**Tested environment:** 
* Chromium 92/Firefox 90 on Ubuntu, Chrome on Mac (unsure of the versions)

**Description**
* When sorting an array of objects (of any length), execution times when calling `orderBy` increase dramatically as the length of the string value being sorted increases.(Times will obviously vary from machine to machine, but I imagine the curve will look mostly the same anywhere)
  *  Given a length of 20 characters, I see times around 0.2ms
  * 100 chars gives  ~13ms
  * 200 chars gives ~210ms
  * 300 chars gives ~1000ms

**Repro**
* I ran the code below in Chromium/Firefox, as well as RunJS to narrow down the issue, and the results were pretty consistent across environments
* The value of `label` in this case is 200 characters in length, and can be changed to see different execution times
```
import { orderBy } from 'natural-orderby';

const inputArray = [
  {
        "label": "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv",
        "value": "foo"
    }
];

const key = 'label';

const time0 = performance.now();

orderBy(inputArray, key);

const time1 = performance.now();

console.log(`call to orderBy took ${time1 - time0}ms`);
```
Output: `'call to orderBy took 204.47000000058324ms'`

**Other notes**
* Breaking up the string with hyphens or white space offsets the increase in execution time
* The number of elements in the array has no significant impact on execution times, unless those items also have similar long unbroken string values

**Comment by JordanAtBridgit** [comment]
I looked around a little with the idea that I might be able to offer up a fix in the form of a PR, and while I don't have a solution yet, the problem seems to be centered around this line here: https://github.com/yobacca/natural-orderby/blob/83f83d33ab4e1da3170838a50361fda0359647f1/src/utils/parseDate.js#L6

Basically, the `RE_DATE` regex takes a long time to run against certain big gross strings, and that slows everything down. Reading and modifying that regex might be a little beyond me, but that's the crux of the issue at least.

**Comment by KnupMan** [comment]
I was impacted by this issue as well and the quick fix was to slice strings to 20-30 characters, so we can sort by a small portion of the strings. But still, it's not good to have a limitation of the first 20-30 characters used for sorting.

**Comment by vladgolubev** [comment]
By changing `parseDate.js` file to the following, I managed to get it work faster by 156,863x:

```ts
// @flow
import type { ParsedNumber } from '../types';
import { RE_DATE } from './regex';

const parseDate = (value: string): ParsedNumber | void => {
  try {
    const parsedDate = Date.parse(value);

    if (!Number.isNaN(parsedDate)) {
      if (RE_DATE.test(value)) {
        return parsedDate;
      }
    }

    return undefined;
  } catch {
    return undefined;
  }
};

export default parseDate;
```

**Comment by vladgolubev** [comment]
@JordanAtBridgit I'ved forked the repo, fixed the performance problem and rewrote it into Typescript:

https://github.com/shelfio/fast-natural-order-by

Check it out

**Comment by JordanAtBridgit** [comment]
@vladgolubev Thanks for picking that up. We still use `natural-orderby` in a few places, so I can make a ticket to check out your fork as an alternative.

**Comment by kylemeenehan** [comment]
@vladgolubev , your change looks really good! Maybe create a PR into this repo? There are over a million weekly downloads for this package, so a lot of people will benefit from your work without having to change their dependencies.
