### ISSUE TITLE
Sorting in orderBy is not stable on some versions of chrome

### ISSUE THREAD

**Issue by mercuriex** [yobacca/natural-orderby#4]
I noticed that in the `baseOrderBy` (hence affecting the top-level `orderBy`) that the standard `Array.prototype.sort()` is being used. On chrome (before version 70), this is not a stable sort algorithm.

Recommend that standard array sort is replaced with https://www.npmjs.com/package/stable or ensure an algorithm such as mergesort is used.

**Comment by oennen** [comment]
Instead of replacing the native `Array.prototype.sort()` used in `baseOrderBy()` I prefer to fix the implementation of `compareMultiple()` and sort equal values by their index of the original array.
