### ISSUE TITLE
node engine in package.json not necessary, causes problems with yarn install

### ISSUE THREAD

**Issue by donp-kitcheck** [yobacca/natural-orderby#70]
When I try to install this package using yarn via `yarn add`, on a system running Node v6.x, the installation fails.

In this module's `package.json` file, there is an entry for the node engine:

```
  "engines": {
    "node": "^8.10.0 || >=9.10.0"
  },
```

Most npm packages that don't have direct dependencies on any node features and they usually don't specify a node version requirement, and use this:

```
  "engines": {
    "node": "*"
  },
```

We are using `yarn` for our node package manager, and it appears that yarn pays attention to this `engine` property, and compares it to the active node version.  So, this means that if I'm running Node v6.x, I can't install `natural-orderby`, because it specifies Node v >8.10 -- even though it doesn't require node.

This should be changed in the npm package's `package.json`, to:

```
  "engines": {
    "node": "*"
  },
```

**Comment by yobacca** [comment]
The node version needs to be at least 6.0.0, because of the use of `Array.isArray()`. I´ll update the `package.json`accordingly.

**Comment by donp-kitcheck** [comment]
Thanks.

`Arrays.isArray()` is native in ES5, so in a front-end use case the node version has no impact.

**Comment by donp-kitcheck** [comment]
Could you also please post a note here when this is packaged and published to npm?

Thanks.

**Comment by yobacca** [comment]
> Thanks.
> 
> `Arrays.isArray()` is native in ES5, so in a front-end use case the node version has no impact.

My fault... I´ll set `engines` as suggested by you. 👍

**Comment by yobacca** [comment]
Fixed version has been published to npm!

Thanks @donp-kitcheck!
